(require 'asdasd-ux-config)

(asdasd-ux-config-load '("asdasd-os-encoding.el"
                         "asdasd-ux-startup.el"
                         "asdasd-ux-keys.el"
                         "asdasd-ux-keys-homerow.el"
                         "asdasd-os-win.el"
                         "asdasd-history.el"
                         "asdasd-note-howm.el"
                         "asdasd-keys-meow.el"
                         "asdasd-ui.el"
                         "asdasd-ui-theme.el"
                         "asdasd-ui-window.el"
                         "asdasd-ui-completion-vertico.el"
                         "asdasd-ux.el"
                         "asdasd-ux-avy.el"
                         "asdasd-ux-window.el"
                         "asdasd-ux-buffer.el"      
                         "asdasd-ux-files.el"
                         "asdasd-ux-minibuffer.el"
                         "asdasd-ux-os.el"
                         "asdasd-ux-help.el"
                         "asdasd-ux-eval.el"
                         "asdasd-ui-completion-vertico.el"
                         "asdasd-ui-tab.el"                        
                         "asdasd-ux-completion-consult.el"
                         "asdasd-ux-completion-consult-embark.el"
                         "asdasd-shell-mingw-bash.el"
                         "asdasd-code.el"
                         "asdasd-code-lang-shells.el"
                         "asdasd-backups.el"
                         "asdasd-text-grep.el"
                         "asdasd-note-org.el"
                         "asdasd-note-org-node.el"
                         "asdasd-note-org-babel.el"
                         "asdasd-note-org-agenda.el"
                         "asdasd-note-org-src.el"
                         "asdasd-code-compile.el"
                         "asdasd-code-hy.el"
                         "asdasd-code-git.el"
                         "asdasd-scratch.el"
                         "asdasd-code-snippet.el"
                         "asdasd-code-structure.el"
                         "asdasd-code-structure-smartparens.el"
                         "asdasd-multifiles.el"
                         "asdasd-code-elisp.el"
                         ;; "asdasd-pdf.el"
                         "asdasd-os-server.el"
                         "asdasd-ux-mark.el"
                         "asdasd-file-project.el"
                         "asdasd-code-lint.el"
                         "asdasd-eglot.el"
                         ))
(provide 'asdasd-init)
